### ISSUE TITLE
Recalculate the width when the container itself is being resized?

### ISSUE THREAD

**Issue by sherryxiao1988** [trotzig/react-with-available-width#3]
Really helpful library!

I have a container whose width depends on if a sidebar is open or not. It would be really great If we could have an option to allow recalculate the width when the container itself is being resized!

Thanks.

**Comment by trotzig** [comment]
I'm embarrassed I didn't see this issue earlier... Sorry for the very late response.

You should be able to do this with `ResizeObserver`. There's a section in the readme about it: 
https://github.com/trotzig/react-with-available-width#reacting-to-size-changes

Let me know how it goes/did go!
