### ISSUE TITLE
Ideas for replacing react-simple-surveyor

### ISSUE THREAD

**Issue by davidtheclark** [trotzig/react-with-available-width#4]
@trotzig: I put together https://github.com/mapbox/react-simple-surveyor based on some things I've already done, and realized that your module is very similar. Are you still working on this and interested in collaborating? If so, I can close out that project and we can merge the best ideas from both. Here are the things I'd like to add:
- Assign only one resize listener, and accumulate callback functions: https://github.com/mapbox/react-simple-surveyor/blob/master/src/survey.js#L6-L19
- That approach also allows for the `resurvey` function: https://github.com/mapbox/react-simple-surveyor/blob/master/src/survey.js#L71 — which is important if you dynamically change the layout and don't want to add some big observer depdendency.
- Add the `debounce` package as a dependency to debounce the resize listener.
- Clarify testing. I'm sort of confused by the testing situation in this repo. I wonder what you think of the test page in react-simple-surveyor.

**Comment by trotzig** [comment]
I'm definitely willing to collaborate! Give me another day and I'll have a look at react-simple-surveyor. I'm afk renovating a house right now, I'll have more time tomorrow. 🙂

**Comment by davidtheclark** [comment]
@trotzig: Awesome. One thing I like about this module (that is not in react-simple-surveyor) is the way it grabs the width from the parent element and then removes the dummy `<div>` entirely.

**Comment by trotzig** [comment]
I'm somewhat swamped with the house renovation right now, so I can only give a few quick comments. Sorry about that, I thought I'd have more time left today, but I underestimated. :)

First of all, @lencioni has [an npm library](https://github.com/lencioni/consolidated-events) for the resize listener problem. We use it in [`react-waypoint`](https://github.com/brigade/react-waypoint), and I believe it's basically doing the same thing that you do in react-simple-surveyor but slightly more robust. I don't know whether it supports the `resurvey` use-case though, but that should be easy to add. 

`debounce` sounds like a good thing. 

I haven't had time to look at your test page, but I believe we've taken similar approaches. I have a test page as well, is it confusing to you? I've only used it myself, so I wouldn't be surprised. :)

**Comment by davidtheclark** [comment]
@trotzig: no worries! There's no big hurry — just thinking at some point I can wipe out react-simple-surveyor. I can look into this things you mention and submit a PR.

**Comment by trotzig** [comment]
Thanks! Wow, I'm kind of surprised how hard it was to balance "real" life with my coding life. All good now though, I'm back at the keyboard for a while again. 😄 

A couple of notes on the temporary `<div>`: 
- It's great for flexbox containers as it won't affect the rendering of the flex item. 
- It's not great when you have stateful components. It changes the DOM structure when measuring, causing unmounts+remount every time we have to measure things again. 

I'm +1 on all the suggestions you left initially. If you end up using consolidated-events, I'm not sure we need debouncing (it has some optimizations built-in).

**Comment by davidtheclark** [comment]
@trotzig: Had some time to circle back to this. Started a PR, but it's not ready yet. Was thinking about your notes ... I think "not great when you have stateful components" is especially problematic. That makes me lean towards adding a `<div>` wrapper around the rendered element. I think it's a valid limitation on the API to specify that:

- This works for block level components, only.
- It is expected that rendered element *will not determine its own width*. It won't work, then, in every flexbox layout, or for a solitary floated element.

Do those caveats sound ok to you?

**Comment by trotzig** [comment]
Yeah, I think that limitation is okay, at least as the default. I'd like to keep support for the non-div however. In the few apps I use react-with-available-width, the `div` was getting in the way in a few places. I don't remember the specifics, but I think they were all in flexbox environments. How about we add an `avoidWrapper` boolean option (name up for discussion) that can be used to control the wrapping strategy?

**Comment by davidtheclark** [comment]
Hm ... I wonder if this is just grounds for keeping two separate modules. Seems like the base functionality is simple enough that creating one module with a couple of significantly code paths just adds dead weight for users.

**Comment by trotzig** [comment]
Might be. Although I think there might be a golden middle path somewhere, where we use a temp div to measure the first time, and then on updates we can use the child. The wrapper-less solution is most elegant in my opinion, and less likely to result in tricky cases for consumers. That being said, my last attempt at trying to implement this failed (can't recall the details right now).

**Comment by trotzig** [comment]
Closing this in an effort to clean out issues in this repo.
